version: '3.9'

services:
  postgres:
    image: 'postgres:16.2'
    container_name: 'homework7'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'